Ewlumpkin/issue2
cooperlees/json2netns pull request #11
Opened 2021-09-10 18:52 UTC by ewlumpkin

Addressed: 
https://github.com/cooperlees/json2netns/pull/10#discussion_r694266375
https://github.com/cooperlees/json2netns/pull/10#discussion_r694266838
https://github.com/cooperlees/json2netns/pull/10#discussion_r694269698
https://github.com/cooperlees/json2netns/pull/10#discussion_r694276191

Comments:
https://github.com/cooperlees/json2netns/pull/10#pullrequestreview-736511089

> Possible future improvements.
> 
> * Specific route based tests
>   
>   * e.g. showing validation works

* Added validation testing and included coverage in setup.py
   * Still need some additional tests for functionality e.g. subprocess mock(s) for route_add

> * Swap the "route/attributes" dict for properties of the "Route" object or make a RouteAttributes named tuple OR dataclass
>   
>   * Why? Stricter typing than a dict

* Changed Route class to dataclass and added typing to attributes

> * From a JSON config we can use **kwargs to construct the objects nicely

* Had some guesses about implementation but wanted to see your idea before changing it.

Open to any and all suggestions

2021-09-11 02:46 UTC, cooperlees requested changes
Love the use of data class - I will prob change some of the other classes to be a dataclass

- I offered some NITs - Nothing big

Do you intend to finish the other unitests with `pass`?

2021-09-11 02:46 UTC, cooperlees commented on src/json2netns/route.py
> +        if ip_network(self.dest_prefix).version == ip_address(self.next_hop_ip).version:
So much cleaner!

2021-09-11 02:46 UTC, cooperlees commented on src/json2netns/tests/netns.py
> +        pass
Forgot to do?

2021-09-11 02:46 UTC, cooperlees commented on src/json2netns/tests/route.py
> +        print(self.config)
```suggestion
        self.config = Config(SAMPLE_JSON_CONF_PATH).load()
```
Debug to remove?

2021-09-11 02:46 UTC, cooperlees commented on src/json2netns/tests/route.py
> +                self.route_list.append(route_obj)
```suggestion
                # create a list of known good route objects to use for testing
                self.route_list.append(route_obj)
```

2021-09-11 02:46 UTC, cooperlees commented on src/json2netns/tests/route.py
> +            )
```suggestion
            self.assertTrue(
                route._Route__proto_match_validated()
            )
```
FYI - This exists

2021-09-11 02:46 UTC, cooperlees commented on src/json2netns/tests/route.py
> +        )
```suggestion
        self.assertFalse(
            self.mismatch_route_obj._Route__proto_match_validated(),
        )
```
Likewise

2021-09-13 19:11 UTC, ewlumpkin commented
> Love the use of data class - I will prob change some of the other classes to be a dataclass
> 
> * I offered some NITs - Nothing big
> 
> Do you intend to finish the other unitests with `pass`?

Awesome, thanks.

Still wrapping my head around patch and mock.  Not really sure how to test those remaining methods at the moment.

2021-09-16 15:20 UTC, cooperlees approved these changes
LGTM - Thanks!

2021-09-16 15:20 UTC, cooperlees commented on setup.py
> +        "json2netns/route.py": 76,
Damn - nice!

2021-09-16 15:20 UTC, cooperlees commented on src/json2netns/tests/netns.py
> +        with patch.object(Route, "get_route") as mock_get_route, patch.object(
TIL - Never used this. This is nice.

2021-09-16 15:20 UTC, cooperlees commented on src/json2netns/tests/route.py
> +            Route, "_Route__route_validated", return_value=True
Dunders everywhere!

2021-09-16 15:20 UTC, merged